name: torchvision_distributed_coco
environment:
  environment_variables:
    - NCCL_DEBUG=INFO
    - NCCL_SOCKET_IFNAME=ens,eth,ib
hyperparameters:
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005
  num_classes: 2
searcher:
  name: single
  metric: iou_segm
  max_length:
    batches: 400
  smaller_is_better: false
resources:
  slots_per_trial: 2
entrypoint: python3 -m determined.launch.torch_distributed python3 train.py
